
version: '3'
services:
  notes:
    container_name: notes
    restart: always
    build: 
      context: .
      dockerfile: dockerfile.notes
    network_mode: host
    ports:
      - 8080:8080
    depends_on:
      - calendar

  calendar:
    container_name: calendar
    restart: always
    build: 
      context: .
      dockerfile: dockerfile.calendar
    network_mode: host
    ports:
      - 9090:9090
