FROM openjdk:11

ENV DD_SERVICE="calendar"
ENV DD_ENV="dev"
ENV DD_VERSION="0.0.1"

LABEL com.datadoghq.tags.service="calendar"
LABEL com.datadoghq.tags.env="dev"
LABEL com.datadoghq.tags.version="0.0.1"

RUN apt-get update -y; apt-get install curl -y

WORKDIR /home/apm-tutorial-java

RUN curl -Lo dd-java-agent.jar https://dtdg.co/latest-java-tracer 

COPY calendar calendar/  
WORKDIR /home/apm-tutorial-java/calendar

#Compile with gradle
RUN ./gradlew clean
RUN ./gradlew bootJar

#Uncomment to run without tracing
ENTRYPOINT ["java", "-jar", "build/libs/calendar-0.0.1-SNAPSHOT.jar"]

#Uncomment to run with tracing
#ENTRYPOINT ["java","-javaagent:../dd-java-agent.jar", "-Ddd.trace.sample.rate=1", "-jar" , "build/libs/calendar-0.0.1-SNAPSHOT.jar"]
