# Unless explicitly stated otherwise all files in this repository are licensed
# under the Apache 2.0 License.
#
# This product includes software developed at Datadog (https://www.datadoghq.com/)
# Copyright 2023 Datadog, Inc.
FROM openjdk:11

RUN apt-get update -y; apt-get install curl -y

WORKDIR /home/apm-tutorial-java

RUN curl -Lo dd-java-agent.jar https://dtdg.co/latest-java-tracer 

COPY calendar calendar/  
WORKDIR /home/apm-tutorial-java/calendar

#Compile with gradle
RUN ./gradlew clean
RUN ./gradlew bootJar

#Uncomment to run without tracing
ENTRYPOINT ["java", "-jar", "build/libs/calendar-0.0.1-SNAPSHOT.jar"]

#Uncomment to run with tracing
#ENTRYPOINT ["java","-javaagent:../dd-java-agent.jar", "-Ddd.trace.sample.rate=1", "-jar" , "build/libs/calendar-0.0.1-SNAPSHOT.jar"]
