#Use when service is locally on Linux and agent is running on docker
version: '3'
services:
  datadog:
    container_name: datadog
    image: "gcr.io/datadoghq/agent:latest"
    pid: host
    network_mode: host
    env_file:
      - ~/sandbox.docker.env
    environment:
      - DD_APM_ENABLED=true
      - DD_APM_NON_LOCAL_TRAFFIC=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup:/host/sys/fs/cgroup:ro
