# Unless explicitly stated otherwise all files in this repository are licensed
# under the Apache 2.0 License.
#
# This product includes software developed at Datadog (https://www.datadoghq.com/)
# Copyright 2023 Datadog, Inc.
#Use when service and agent are running on docker
version: '3'
services:
  notes:
    container_name: notes
    restart: always
    build: 
      context: ../
      dockerfile: notes/dockerfile.notes.maven
    ports:
      - 8080:8080
    labels:
      - com.datadoghq.tags.service="notes"
      - com.datadoghq.tags.env="dev"
      - com.datadoghq.tags.version="0.0.1"
    environment:
      - DD_SERVICE=notes
      - DD_ENV=dev
      - DD_VERSION=0.0.1
      - DD_AGENT_HOST=datadog-agent
#      - CALENDAR_HOST=calendar
#    depends_on:
#      - calendar
#      - datadog-agent

#  calendar:
#    container_name: calendar
#    restart: always
#    build: 
#      context: ../
#      dockerfile: calendar/dockerfile.calendar.maven
#    labels:
#       - com.datadoghq.tags.service="calendar"
#       - com.datadoghq.tags.env="dev"
#       - com.datadoghq.tags.version="0.0.1"
#    environment:
#       - DD_SERVICE=calendar
#       - DD_ENV=dev
#       - DD_VERSION=0.0.1
#       - DD_AGENT_HOST=datadog-agent
#    ports:
#      - 9090:9090
#    depends_on:
#      - datadog-agent
      
#  datadog-agent:
#    container_name: datadog-agent
#    image: "gcr.io/datadoghq/agent:latest"
#    pid: host
#    environment:
#      - DD_API_KEY=<DD_API_KEY_HERE>
#      - DD_APM_ENABLED=true
#      - DD_APM_NON_LOCAL_TRAFFIC=true
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
#      - /proc/:/host/proc/:ro
#      - /sys/fs/cgroup:/host/sys/fs/cgroup:ro 
      
