# Unless explicitly stated otherwise all files in this repository are licensed
# under the Apache 2.0 License.
#
# This product includes software developed at Datadog (https://www.datadoghq.com/)
# Copyright 2023 Datadog, Inc.
#Use when running application on k8s or related places like AWS EKS or GCP GKE
#Creates bare application images as other variables will be set in other k8s files
version: '3'
services:
  notes:
    container_name: notes
    build: 
       context: ../
       dockerfile: notes/dockerfile.notes.maven

  calendar:
    container_name: calendar
    build: 
      context: ../
      dockerfile: calendar/dockerfile.calendar.maven
    
