#Use when service is running on docker and agent is running locally on Linux
#Ensure that agent is configured for container data by setting apm_config and apm_non_local_traffic:true in .yaml file
#If docker version less than 20.10
  #replace host.docker.internal with IP of docker0 to give container access to agent on host
  #remove extra hosts configurations on containers
version: '3'
services:
  notes:
    container_name: notes
    restart: always
    build: 
       context: ../
       dockerfile: notes/dockerfile.notes
    ports:
      - 8080:8080
    depends_on:
      - calendar
    environment:
      - DD_AGENT_HOST=host.docker.internal
      - CALENDAR_HOST=host.docker.internal
    extra_hosts:
      - "host.docker.internal:host-gateway"

  calendar:
    container_name: calendar
    restart: always
    build: 
      context: ../
      dockerfile: calendar/dockerfile.calendar
    ports:
      - 9090:9090
    environment:
      - DD_AGENT_HOST=host.docker.internal
    extra_hosts:
      - "host.docker.internal:host-gateway"
    
