/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    java
    application
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    implementation("org.springframework.boot:spring-boot-starter-data-jpa:2.7.1")
    implementation("org.springframework.boot:spring-boot-starter-jersey:2.7.1")
    runtimeOnly("com.h2database:h2:2.1.214")
    testImplementation("org.springframework.boot:spring-boot-starter-test:2.7.1")
}

group = "com.datadog.example"
version = "0.0.1-SNAPSHOT"
description = "notes"
java.sourceCompatibility = JavaVersion.VERSION_11

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

application {
    mainClass.set("com.datadog.example.notes.NotesApplication")
}
